import React from 'react';
import Header from '../layout/header';
import Footer from '../layout/footer';
import Head from 'next/head'

const SeatSelection = ({ sections }) => {
  return (
    <div>
      <Head>
        <title>Seat Selection | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 style={{textAlign: 'center'}}>Seat Selection</h1>
      <ul>
        {sections.map((section) => (
          <li key={section.sectionNumber}>

            <p style={{textAlign: 'center'}}>{`Section Number: ${section.sectionNumber}`}</p>
            <p style={{textAlign: 'center'}}>{`Price: ${section.price}`}</p>

          <div style={{display: 'flex', flexDirection:'column', alignItems:'center'}}>
          <a href="./myAccount/orderHistory">
            <button>Purchase Ticket</button>
          </a>
          </div>
            
          </li>
        ))}
      </ul>
      <Footer />
    </div>
  );
};

export default SeatSelection;