import React from 'react';
import Header from '../layout/header';
import Footer from '../layout/footer';
import Head from 'next/head'

const TicketList = (tickets) => {
  return (
    <div>
      <Head>
        <title>Account Tickets | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 style={{textAlign: 'center'}}>My Tickets</h1>
      <div style={{display: 'flex', justifyContent: 'center'}}>
      <ul>
        {tickets.map((ticket) => (
          <li key={ticket.ticketId}>
            <p>{`Ticket ID: ${ticket.ticketId}`}</p>
            <p>{`Event ID: ${ticket.eventId}`}</p>
            <p>{`Section: ${ticket.section}`}</p>
            <p>{`Price: ${ticket.price}`}</p>
          </li>
        ))}
      </ul>
      </div>
      <Footer />
    </div>
  );
};

export default TicketList;