import React from 'react';
import Header from '../layout/header';
import Footer from '../layout/footer';
import Head from 'next/head'

const OrderHistory = ({ orders }) => {
  return (
    <div>
      <Head>
        <title>Order History | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 style={{textAlign: 'center'}}>Order History</h1>
      <div style={{display: 'flex', justifyContent: 'center'}}>
      <ul>
        {orders.map((order) => (
          <li key={order.invoiceNumber}>
            <p>{`Event ID: ${order.eventId}`}</p>
            <p>{`Price: ${order.price}`}</p>
            <p>{`Invoice Number: ${order.invoiceNumber}`}</p>
          </li>
        ))}
      </ul>
      </div>
      <Footer />
    </div>
  );
};

export default OrderHistory;