import Head from 'next/head'
import Header from '../layout/header'
import Footer from '../layout/footer'
import {grid2Classes, Typography} from '@mui/material';
import Grid from '@mui/material/Grid'; // Grid version 1
import Grid2 from '@mui/material/Unstable_Grid2'; // Grid version 2
import Stack from '@mui/material/Stack'
import Link from '@mui/material/Link';
import Button from '@mui/material/Button';

function search () {
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Search Event | Ticketbass-Turd</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />


                <Footer />
            </main>
        </>
    )
}
