import Head from 'next/head'
import Header from './layout/header'
import Footer from './layout/footer'
import {Typography} from "@mui/material";
import Link from "@mui/material/Link";
import Stack from "@mui/material/Stack";

export async function getServerSideProps({query}) {
    const response = await fetch(`http://127.0.0.1:8000/api/payment/${query.user}/${query.eventID}/${query.quantity}/${query.cardNum}/${query.cvv}/${query.name}/${query.expiryMonth}/${query.expiryYear}`, {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
        },
    });
    const data = await response.json();
    return {props: {data}}
}

function Purchase({data}) {
    if (data.success.toString() === "true") {
        return (
            <Stack alignItems={'center'} sx={{mt: 5}} spacing={3}>
                <Typography variant="h1">Success</Typography>
                <Typography variant="h5">Thank you for your purchase!</Typography>
                <Link href={'/myAccount/currentTickets'}>
                    <Typography variant="h4">View your tickets</Typography>
                </Link>

            </Stack>
        )
    } else {
        return (
            <div>
                <Stack alignItems={'center'} sx={{mt: 5}} spacing={3}>
                    <Typography variant="h1">Error</Typography>
                    <Typography variant="h5">There was an error processing your payment.</Typography>
                    <Typography variant="h5">Please try again.</Typography>
                </Stack>
            </div>
        )
    }
}


export default function Checkout({data}) {
    return (
        <>
            <Head>
                <title id={'title'}>Checkout | Ticketbass-Turd</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Purchase data={data}/>
                <Footer/>
            </main>
        </>
    )
}
