import Head from 'next/head'
import Header from './layout/header'
import Footer from './layout/footer'
import {Typography} from '@mui/material';
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import {useState, useEffect} from "react";
import {useSearchParams} from "next/navigation";

export function getEvent() {
  const [data, setData] = useState(null);
  let name = null;

  useEffect(() => {
    const fetchData = () => {
      fetch(`http://localhost:8000/api/get/event/${new URLSearchParams(window.location.search).get('id')}`, {method: 'GET', headers: {'Content-Type': 'application/json', 'Alow-Control-Allow-Origin': '*'}})
          .then(data => data.json())
          .then(data => {
            name = data.result.name;
            setData(data);
          })
    };
    fetchData();
  }, []);

  return (
      <div>
          <Typography variant={'h4'}>{name}</Typography>
      </div>
  )
}

export default function Events() {
  return (
      <>
        <Head>
          <title>Event Info | Ticketbass-Turd</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header />
            {getEvent()}
          <Footer/>
        </main>
      </>
  )
}
