import Head from 'next/head'
import Header from './layout/header'
import Footer from './layout/footer'
import {Typography} from '@mui/material';
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import Box from '@mui/material/Box';

export default function Home() {
    return (
        <>
            <Head>
                <title>Login | Ticketbass-Turd</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Stack alignItems={'center'} justifyContent={'center'} sx={{pt:15, backgroundColor: 'white', width: "50%", height: "50%", p:20}}>
                    <TextField sx={{m:5, p: 2}} id={'email'} label={'Email'} variant={'outlined'}></TextField>
                    <TextField sx={{m:5, p: 2}} id={'pass'} label={'Password'} variant={'outlined'}></TextField>
                    <Button sx={{mt:5}} variant={'contained'}>Login</Button>
                </Stack>
                <Footer/>
            </main>
        </>
    )
}
