import * as React from 'react';
import { sizing } from '@mui/system';
import Header from './layout/header';
import Footer from './layout/footer';
import Head from 'next/head'

function App() {
  return (
    <div>
      <Head>
        <title>FAQ | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <h2>Account Info</h2>
          <button>Change Account Info</button>
        </section>
        <section>
          <h2>Current Tickets</h2>
          <a href="./myAccount/currentTickets">
            <button>Get Current Tickets</button>
          </a>
        </section>
      </main>
      <Footer />
    </div>
  );
}

export default App;