import * as React from 'react';
import { sizing } from '@mui/system';
import Header from './layout/header';
import Footer from './layout/footer';
import Head from 'next/head'
import Stack from "@mui/material/Stack";
import {Typography} from "@mui/material";
import Button from "@mui/material/Button";

function App() {
    return (
        <div>
            <Head>
                <title>My Account | Ticketbass-Turd</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main>
                <Stack alignItems={'center'} spacing={2} sx={{m: 10}}>
                    <Typography variant={'h2'}>Account Info</Typography>
                    <Button style={{maxWidth: '5iem'}} sx={{m: 5}} variant={'contained'}
                            onClick={() => {
                                window.location.href = '/updateAccount'
                            }}
                    >Update Account</Button>

                    <Typography variant={'h2'} style={{marginTop: '5%'}}>Tickets</Typography>
                    <Button style={{maxWidth: '5iem'}} sx={{m: 5}} variant={'contained'}
                            onClick={() => {
                                window.location.href = '/myAccount/currentTickets'
                            }}
                    >View Tickets</Button>
                </Stack>


            </main>
            <Footer/>
        </div>
    );
}

export default App;