import Head from 'next/head'
import Header from './layout/header'
import Footer from './layout/footer'
import {Typography} from '@mui/material';
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';



const Register = async () => {
    const email = document.getElementById('email').value;
    const pass = document.getElementById('pass').value;
    const first = document.getElementById('first').value;
    const last = document.getElementById('last').value;
    const phone = document.getElementById('phone').value;

    const response = await fetch(`http://127.0.0.1:8000/api/create_account/${email}/${pass}/${first}/${last}/${phone}`, {method: 'GET', headers: {'Content-Type': 'application/json', 'Alow-Control-Allow-Origin': '*'}})
    const data = await response.json();
    if (data.success !== false && data.success !== undefined) {
        alert('Registration Successful, redirecting to login page.');

        window.location.href = 'http://localhost:3000/login';
    } else {
        alert('Registration Failed. Please make sure you have entered a valid email and password and try again.');
    }

}

export default function RegisterPage() {
    return (
        <>
            <Head>
                <title>Register | Ticketbass-Turd</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header />
                <Stack alignItems={'center'} justifyContent={'center'} sx={{pt:15, backgroundColor: 'white', p:3, m: '20%', border: '5px solid grey', borderRadius: '25px'}}>
                    <Typography sx={{m:1, color: 'black'}} variant={'h4'}>Register</Typography>
                    <TextField sx={{m:1}} id={'email'} label={'Email'} variant={'outlined'}></TextField>
                    <TextField sx={{m:1}} id={'pass'} label={'Password'} variant={'outlined'}></TextField>
                    <TextField sx={{m:1}} id={'first'} label={'First Name'} variant={'outlined'}></TextField>
                    <TextField sx={{m:1}} id={'last'} label={'Last Name'} variant={'outlined'}></TextField>
                    <TextField sx={{m:1}} id={'phone'} label={'Phone Number'} variant={'outlined'}></TextField>
                    <Button sx={{m:1}} variant={'contained'}
                            onClick={() => {
                                Register();
                            }}
                    >Register</Button>
                    <Typography sx={{m:1, color: 'black'}} variant={'body1'}>Already have an account? <a style={{color: 'blue'}} href={'/login'}>Login now</a></Typography>
                </Stack>
                <Footer/>
            </main>
        </>
    )
}
