import Head from 'next/head'
import Header from './layout/header'
import Footer from './layout/footer'
import {Typography} from '@mui/material';
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button';
import {useState, useEffect} from "react";
import Box from "@mui/material/Box";

let placeholderUser = {
  "user_id": "1",
  "first_name": "Loading...",
  "last_name": "Loading...",
  "email": "Loading...",
  "phone_num": "Loading...",
}

function updateWindowTitle(title) {
  document.title = title;
}

export function getEvent() {
  const [venueInfo, setVenueInfo] = useState([]);

  useEffect(() => {
    const fetchVenue = () => {
      fetch(`http://localhost:8000/api/get/user/${new URLSearchParams(window.location.search).get('id')}`, {method: 'GET', headers: {'Content-Type': 'application/json', 'Alow-Control-Allow-Origin': '*'}})
          .then(data => data.json())
          .then(data => {
            setVenueInfo(data);
            if (data.result !== undefined) {
              placeholderUser.user_id = data.result.user_id;
              placeholderUser.first_name = data.result.first_name;
              placeholderUser.last_name = data.result.last_name;
              placeholderUser.email = data.result.email;
              placeholderUser.phone_num = data.result.phone_num;

            } else {
              placeholderUser.name = "Host Not Found";
            }
          })
    }
    fetchVenue();
  }, []);

  if (placeholderUser.name === "Host Not Found") {
    return (
        <div>
          <Stack alignItems={'center'} sx={{mt:10}}>
            <Typography variant={'h1'}>{placeholderUser.name}</Typography>
            <Button style={{maxWidth: '5iem'}} sx={{m:5}} variant={'contained'}
                    onClick={() => {
                      window.location.href = '/'
                    }}
            >Back to search</Button>
          </Stack>
        </div>);
  }

  return (
      <div>
        <Box>
          <Stack align={'center'} spacing={4} sx={{mt:5}}>

            <Typography variant={'h1'}>{`${(placeholderUser.first_name)} ${(placeholderUser.last_name)}`}</Typography>
            <Typography variant={'h6'}>{`Email: ${(placeholderUser.email)}`}</Typography>
            <Typography variant={'h6'}>{`Phone Number: ${(placeholderUser.phone_num)}`}</Typography>
          </Stack>

        </Box>

      </div>
  )
}

export default function Events() {
  return (
      <>
        <Head>
          <title id={'title'}>Event Info | Ticketbass-Turd</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header />
          {getEvent()}
          <Footer/>
        </main>
      </>
  )
}
