import React from 'react';
import Header from './layout/header';
import Footer from './layout/footer';
import Head from 'next/head'

const EventPage = ({ eventId, venue, eventName, eventDate, hostName, minAge }) => {
  return (
    <div>
      <Head>
        <title>Event | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p style={{textAlign: 'center'}}>{`Event ID: ${eventId}`}</p>
      <h1 style={{textAlign: 'center'}}>{eventName}</h1>
      <p style={{textAlign: 'center'}}>{`Venue: ${venue}`}</p>
      <p style={{textAlign: 'center'}}>{`Date: ${eventDate}`}</p>
      <p style={{textAlign: 'center'}}>{`Minimum Age: ${minAge}`}</p>
      <p style={{textAlign: 'center'}}>{`Host: ${hostName}`}</p>
      <Footer />
    </div>
  );
};

export default EventPage;