import React from 'react';
import Head from 'next/head'

const EventPage = ({ eventId, venue, eventName, eventDate, hostName, minAge }) => {
  return (
    <div>
      <Head>
        <title>Event | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{`Event ID: ${eventId}`}</p>
      <h1>{eventName}</h1>
      <p>{`Venue: ${venue}`}</p>
      <p>{`Date: ${eventDate}`}</p>
      <p>{`Minimum Age: ${minAge}`}</p>
      <p>{`Host: ${hostName}`}</p>
    </div>
  );
};

export default EventPage;