import React from 'react';
import Header from './layout/header';
import Footer from './layout/footer';
import Head from 'next/head'

const UserPage = ({ firstName, lastName, userId }) => {
  return (
    <div>
      <Head>
        <title>User | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1 style={{textAlign: 'center'}}>{`${firstName} ${lastName}`}</h1>
      <p style={{textAlign: 'center'}}>{`User ID: ${userId}`}</p>
      <Footer />
    </div>
  );
};

export default UserPage;