import React from 'react';
import Head from 'next/head'

const UserPage = ({ firstName, lastName, userId }) => {
  return (
    <div>
      <Head>
        <title>User | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{`${firstName} ${lastName}`}</h1>
      <p>{`User ID: ${userId}`}</p>
    </div>
  );
};

export default UserPage;