import React from 'react';
import Head from 'next/head'

const VenuePage = ({ venueId, venueName, venueAddress, maxCapacity, description }) => {
  return (
    <div>
      <Head>
        <title>Venue | Ticketbass-Turd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>{`Venue Id: ${venueId}`}</p>
      <h1>{venueName}</h1>
      <p>{`Address: ${venueAddress}`}</p>
      <p>{`Max Capacity: ${maxCapacity}`}</p>
      <p>{`Description: ${description}`}</p>
    </div>
  );
};

export default VenuePage;